### ISSUE TITLE
README instructions for test solr_wrapper wrong

### ISSUE THREAD

**Issue by jrochkind** [samvera/active_fedora#1216]
solr_wrapper says:

> If you want to run the tests manually, follow these instructions:
>      solr_wrapper

> To start FCRepo, open another shell and run:
> .    fcrepo_wrapper -p 8984

However solr_wrapper seems to also need a port, the tests are looking for solr at `solr_wrapper -p 8986`

**Comment by atz** [comment]
Looks like it has been updated.
