### ISSUE TITLE
ActiveFedora.clean! should delete permission template entries from the database

### ISSUE THREAD

**Issue by elrayle** [samvera/active_fedora#1314]
### Descriptive summary

ActiveFedora.clean! removes all objects from Fedora and Solr.  The entries in the permission_template and permission_template_access tables are tightly coupled to the Collection and AdminSet objects.  When those are deleted from Fedora/Solr, the associated permission templates entries in the database should also be deleted.

### Rationale

Clean should clean all entries in Fedora and Solr, and database entries that are tightly coupled with the Fedora/Solr objects.

### Expected behavior

When ActiveFedora.clean! is run, all entries in permission_template and permission_template_access tables in the database are also deleted.

We use this locally to do this...

```
    require 'active_fedora/cleaner'
    ActiveFedora::Cleaner.clean!
    # PermissionTemplates are tightly coupled to admin sets and collections.  When they are removed using clean!, the
    # associated database entries for permission templates also have to be deleted.
    Hyrax::PermissionTemplateAccess.destroy_all
    Hyrax::PermissionTemplate.destroy_all
```

### Actual behavior

Permission template database entries are not deleted when clean! is run.  This causes an exception to be thrown when the default admin set is recreated complaining that a PermissionTemplate with this source_id already exists.  

Although this could occur for any admin set or collection, it is unexpected because the ids are generated.  The default admin set has a hardcoded id `default/adminset` so it will always get the exception.

Even though there isn't a conflict for other admin sets and collections, it will still leave dead entries in the database for source_ids that no longer exist.

**Comment by jcoyne** [comment]
ActiveFedora only deletes Fedora objects.  PermissionTemplates are database objects and ActiveFedora has no awareness of them.
