### ISSUE TITLE
Convert TODO comments to issues

### ISSUE THREAD

**Issue by botimer** [samvera/active_fedora#1319]
There are about 20 TODO comments throughout the code. These should be converted to issues and referenced, or pruned if the person reviewing can decide that they are no longer relevant.

**Comment by jrgriffiniii** [comment]
The following issues were created from these TODO comments:
- https://github.com/samvera/active_fedora/issues/1329
- https://github.com/samvera/active_fedora/issues/1330
- https://github.com/samvera/active_fedora/issues/1331
- https://github.com/samvera/active_fedora/issues/1332
- https://github.com/samvera/active_fedora/issues/1333
- https://github.com/samvera/active_fedora/issues/1334
- https://github.com/samvera/active_fedora/issues/1335
- https://github.com/samvera/active_fedora/issues/1336
- https://github.com/samvera/active_fedora/issues/1337
- https://github.com/samvera/active_fedora/issues/1338
- https://github.com/samvera/active_fedora/issues/1339
- https://github.com/samvera/active_fedora/issues/1340
- https://github.com/samvera/active_fedora/issues/1341
- https://github.com/samvera/active_fedora/issues/1342
- https://github.com/samvera/active_fedora/issues/1343
- https://github.com/samvera/active_fedora/issues/1344
- https://github.com/samvera/active_fedora/issues/1345
- https://github.com/samvera/active_fedora/issues/1346
- https://github.com/samvera/active_fedora/issues/1347

**Comment by botimer** [comment]
I think we should back through the source and link the issues above. I'm happy to do that. Thanks for working through all of them, @jrgriffiniii.

**Comment by botimer** [comment]
Okay, PR opened that I think closes this one off. Happy for you to review, @jrgriffiniii.
