### ISSUE TITLE
Confirm copyright statement/years

### ISSUE THREAD

**Issue by botimer** [samvera/active_fedora#1320]
The copyright statement in LICENSE.md hasn't been updated in some time. Please check that it is as intended, or make the appropriate updates.

**Comment by no-reply** [comment]
See also samvera-labs/maintenance#3. This license should follow the template there.

**Comment by barmintor** [comment]
It seems like minimally, Penn State (2011), WGBH and Notre Dame (2012) need to be added. That would capture most of the top 8 contributors' sponsoring partners at time of contribution.
