### ISSUE TITLE
Solr config refers to deprecated LatLonType

### ISSUE THREAD

**Issue by jcoyne** [samvera/active_fedora#1370]
```
    <fieldType name="location" class="solr.LatLonType" subFieldSuffix="_coordinate"/>
```

I don't think we're using this anywhere. Can we drop this field type or do we want to migrate to one of: `LatLonPointSpatialField`, `SpatialRecursivePrefixTreeField`, or `RptWithGeometrySpatialField`?

**Comment by no-reply** [comment]
Shall we just remove it? It seems like it won't hurt existing adopters (who will have generated from the old template), and will improve matters for new users.
