### ISSUE TITLE
Ruby 2.7 - warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by prdanelli** [samvera/active_fedora#1454]
Hello, firstly, i would like to say thank you for the work you have invested in this project, its very much appreciated.

When using Ruby 2.7 and AF 12.2.x, Ruby gives a deprecation warning: 

```
/usr/local/bundle/gems/active-fedora-12.2.3/lib/active_fedora/file.rb:182: warning: URI.escape is obsolete
```
According to this Ruby post, https://bugs.ruby-lang.org/issues/17309, the issue could be resolved by replacing all instances of `URI.escape` with `URI::DEFAULT_PARSER.escape`. 

Is this something that is possible or would be welcomed as a PR?

Thank you, 
Paul.

**Comment by jcoyne** [comment]
Yes, please make a PR if you are able.

**Comment by jrgriffiniii** [comment]
Resolved with https://github.com/samvera/active_fedora/pull/1456
