### ISSUE TITLE
rdf 3.2.5 causes superclass mismatch for class DateTime

### ISSUE THREAD

**Issue by cziaarm** [samvera/active_fedora#1466]
` .../active-fedora-13.2.5/lib/active_fedora.rb:16:in '<class:Literal>': superclass mismatch for class DateTime (TypeError)`

rdf 3.2.4, no problem

**Comment by cziaarm** [comment]
Thanks Chris, we'll hold with rdf 3.2.4 until then.

**Comment by cjcolvar** [comment]
ActiveFedora 13.2.6 was released with a fix for this issue but it introduced 3 failing tests in Hyrax around date precision beyond milliseconds.  This version of the gem was yanked until we have a better fix which should hopefully be soon.  For now pinning rdf  to < 3.2.5 might be your best bet.
