### ISSUE TITLE
Support Ruby 3.0.3

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/active_fedora#1470]
This is derived from https://github.com/samvera/maintenance/issues/77

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/active_fedora/commit/49c0f0dfd9fbdcaba196db1df5ab641704c5d4ad finally ensures that `bundle install` can reliably install Gem dependencies, however the following `psych` bug is now raised:

```bash
An error occurred while loading ./spec/integration/associations_spec.rb.
Failure/Error: fedora_yml = YAML.safe_load(config_erb, [], [], true) # allow YAML aliases

ArgumentError:
  wrong number of arguments (given 4, expected 1)
# ./vendor/bundle/gems/psych-4.0.3/lib/psych.rb:323:in `safe_load'
# ./lib/active_fedora/file_configurator.rb:111:in `load_fedora_config'
```

**Comment by jrgriffiniii** [comment]
For releases of `ldp` following 0.4.1, Ruby 2.y.z releases are required (please compare https://rubygems.org/gems/ldp/versions/0.4.1 and https://rubygems.org/gems/ldp/versions/0.5.0)

**Comment by jrgriffiniii** [comment]
The method signature for https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/model/graph.rb#L106 has changed, and https://github.com/ActiveTriples/ActiveTriples/blob/develop/lib/active_triples/rdf_source.rb#L125 must be updated for this.

**Comment by jrgriffiniii** [comment]
This is also blocked by another release of `ldp`:

```
active-fedora was resolved to 13.2.7, which depends on
      ldp (>= 1.0) was resolved to 1.0.3, which depends on
        Ruby (~> 2.0)
```

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/active_fedora/commit/55ef06e259c5859a7d84754955f3cc7d5355664e seems to still be blocked until I can port Lando for running the test suites.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/active_fedora/compare/updating-active-triples?expand=1 advances this with as much labor as I can provide before the next scheduled Developer Congress.

**Comment by jrgriffiniii** [comment]
`POST` requests are submitted with erroneously-formatted parameters:

> "\n [<info:fedora/fedora-system:def/model#hasModel> \"Image\"] .\n

These brackets should not be present here.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/active_fedora/commit/c53f863a0f408f00fd170ffcc70876cccda4db9a ensures that nodes for ordered list nodes can be resolved from LDP servers.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/active_fedora/commit/40293154ffe55d4aef4badd72294d8c854ab5505 was needed as a starting point for me to understand why `Proxy` models are not being resolved from `ListSources` when `ActiveFedora::Base#reload` is invoked (they are persisted, but for some reason, the cache for these is not repopulated for the Associations).

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/active_fedora/commit/e62982957a21433490e00864a57acf171b9d1292 is a potential solution, but I am still struggling to understand why this was breaking with a simple Ruby/Rails upgrade.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/active_fedora/commit/49c1203ea80042db64e1fa99ea3481ac75a69fa9 was needed to address certain cases where duplication was occurring, but this does not seem to correctly address the cases for ordering elsewhere.

**Comment by cjcolvar** [comment]
Draft PR: https://github.com/samvera/active_fedora/pull/1489
