### ISSUE TITLE
Error when creating an ActiveFedora::Base model  that contains a Datastream that refers to a Disseminator

### ISSUE THREAD

**Issue by simonlamb** [samvera/active_fedora#291]
When an ActiveFedora::Base model contains a has_metadata declaration that includes the config options of [:disseminator] and [:control_group] "E", the object will fail to save due to the calling of a long deprecated method "config_for_environment".

The following line:-

https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/datastreams.rb#L35

``` ruby
ds.dsLocation= "#{ActiveFedora.config_for_environment[:url]}/objects/#{pid}/methods/#{ds_config[:disseminator]}"
```

can be replaced with:-

``` ruby
ds.dsLocation = "#{ ActiveFedora.config.credentials[:url] }/objects/#{pid}/methods/#{ds_config[:disseminator]}"
```

I'm happy to submit a pull request for this issue.  However due to local project pressures it will be in the new year.

**Comment by jrgriffiniii** [comment]
Greater than 10 years old, closing.
