### ISSUE TITLE
NomDatastream must implement #update_indexed_attributes

### ISSUE THREAD

**Issue by jeremyf** [samvera/active_fedora#31]
The NomDatastream does not implement #update_indexed_attributes

A datastream declared via ActiveFedora::Base.has_metadata is expected to implement #update_indexed_attributes

Is there a specific expected interface that a Datastream should adhere to?

It appears the missing methods for NomDatastream are:
- #updated_indexed_attributes
- #term_values

**Comment by atz** [comment]
In the intervening 4.5 years, `NomDatastream` has been deprecated and removed.  Closing this.
