### ISSUE TITLE
RDF wiki, lesson 2 should use datastreams

### ISSUE THREAD

**Issue by jcoyne** [samvera/active_fedora#359]
Currently this page: https://github.com/projecthydra/active_fedora/wiki/Lesson:-Use-RDF-to-Represent-Flat-Metadata-like-Dublin-Core uses `include ActiveFedora::RdfObject` but it might be easier to learn if we just extended `ActiveFedora::NtriplesRdfDatastream` because that's how this would appear in a project.

Like this:
https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/datastreams/generic_file_rdf_datastream.rb

**Comment by atz** [comment]
@jcoyne I think this is closable as datastreams are pretty much gone now.
