### ISSUE TITLE
Optimize reads

### ISSUE THREAD

**Issue by jcoyne** [samvera/active_fedora#463]
Look into reverting these commits:
https://github.com/projecthydra-labs/fedora_lens/commit/a8a882e08a9d6e2b8192629705ec74b8a6433c62
https://github.com/projecthydra-labs/fedora_lens/commit/7b30a08bc2e8f788ad6d6362e1fbf701b5938101

**Comment by atz** [comment]
Doubt this is relevant anymore.  @jcoyne, @tpendragon: comment?

**Comment by jcoyne** [comment]
No, we dropped fedora_lens long ago.
